/**
 *
 * Nikie Jean Evangelista,Jowin Earl Ganapin BSCS2-B
 */
 
import javax.swing.*;
import java.awt.*;

public class AreaConverter extends javax.swing.JFrame {

    public final double pi = 3.14;
    private double area, perimeter, radius = 0, length = 0, width = 0, side = 0;
    private String temp, temp2;
    
    /**
     * Creates new form AreaConverter
     */
    public AreaConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        rdoCircle = new javax.swing.JRadioButton();
        rdoRectangle = new javax.swing.JRadioButton();
        rdoSquare = new javax.swing.JRadioButton();
        lblCircle = new javax.swing.JLabel();
        lblRectangle = new javax.swing.JLabel();
        lblSquare = new javax.swing.JLabel();
        txtInputCR = new javax.swing.JTextField();
        txtInputUL = new javax.swing.JTextField();
        txtInputSS = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtInputUW = new javax.swing.JTextField();
        rdoGetAC = new javax.swing.JRadioButton();
        rdoGetPC = new javax.swing.JRadioButton();
        rdoGetRA = new javax.swing.JRadioButton();
        rdoGetRP = new javax.swing.JRadioButton();
        rdoGetSA = new javax.swing.JRadioButton();
        rdoGetSP = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtGetResultA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGetResultB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtGetResultC = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        rdoCircle.setText("Circle");
        rdoCircle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoCircleActionPerformed(evt);
            }
        });

        rdoRectangle.setText("Rectangle");
        rdoRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoRectangleActionPerformed(evt);
            }
        });

        rdoSquare.setText("Square");
        rdoSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoSquareActionPerformed(evt);
            }
        });

        lblCircle.setText("Enter unit radius:");

        lblRectangle.setText("Enter unit length:");

        lblSquare.setText("Enter a number:");

        jLabel4.setText("Enter unit width:");

        rdoGetAC.setText("Calculate the Area");
        rdoGetAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoGetACActionPerformed(evt);
            }
        });

        rdoGetPC.setText("Calculate the Circumference");
        rdoGetPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoGetPCActionPerformed(evt);
            }
        });

        rdoGetRA.setText("Calculate the Area");
        rdoGetRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoGetRAActionPerformed(evt);
            }
        });

        rdoGetRP.setText("Calculate the Perimeter");
        rdoGetRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoGetRPActionPerformed(evt);
            }
        });

        rdoGetSA.setText("Calculate the Area");
        rdoGetSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoGetSAActionPerformed(evt);
            }
        });

        rdoGetSP.setText("Calculate the Perimeter");
        rdoGetSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoGetSPActionPerformed(evt);
            }
        });

        jLabel5.setText("Result:");

        txtGetResultA.setEnabled(false);

        jLabel6.setText("Result:");

        jLabel7.setText("Result:");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnAbout.setText("About");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoGetAC)
                            .addComponent(rdoCircle)
                            .addComponent(lblCircle)
                            .addComponent(txtInputCR, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdoGetPC)
                            .addComponent(jLabel5)
                            .addComponent(txtGetResultA, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(rdoGetRP)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(rdoGetRA, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtInputUW, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRectangle, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdoRectangle, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtInputUL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(22, 22, 22)))
                            .addComponent(jLabel6)
                            .addComponent(txtGetResultB, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(rdoGetSP)
                            .addComponent(rdoGetSA)
                            .addComponent(rdoSquare)
                            .addComponent(lblSquare)
                            .addComponent(txtInputSS, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGetResultC, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(btnReset)
                        .addGap(31, 31, 31)
                        .addComponent(btnExit)
                        .addGap(29, 29, 29)
                        .addComponent(btnAbout)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdoSquare)
                        .addGap(18, 18, 18)
                        .addComponent(lblSquare)
                        .addGap(18, 18, 18)
                        .addComponent(txtInputSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(rdoGetSA)
                        .addGap(18, 18, 18)
                        .addComponent(rdoGetSP)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtGetResultC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoCircle)
                            .addComponent(rdoRectangle))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCircle)
                            .addComponent(lblRectangle))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInputCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInputUL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtInputUW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoGetAC)
                            .addComponent(rdoGetRA))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoGetPC)
                            .addComponent(rdoGetRP))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGetResultA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGetResultB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnAbout)
                    .addComponent(btnReset))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void rdoCircleActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if(rdoCircle.isSelected())
        {
            disabledSetB();
            disabledSetC();
            txtInputCR.setEnabled(true);
            rdoGetAC.setEnabled(true);
            rdoGetPC.setEnabled(true);
        }
    }                                         

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {                                         
        temp = "";
        temp2 = "";
        area = 0;
        perimeter = 0;
        length = 0;
        width = 0;
        disableAllItems();
        enabledFirstThree();
    }                                        

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {                                        
        dispose();
    }                                       

    private void formWindowActivated(java.awt.event.WindowEvent evt) {                                     
        disableAllItems();
        enabledFirstThree();
    }                                    

    private void rdoGetACActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(rdoGetAC.isSelected())
        {
            rdoGetPC.setEnabled(false);
            try
            {
                temp = txtInputCR.getText();
                radius = Double.parseDouble(temp);
            }
            catch(NumberFormatException errors)
            {
                JOptionPane.showMessageDialog(null, "Enter the correct input!");   
            }
            finally
            {
                area = pi * (radius * radius);
                txtGetResultA.setText("Area: " + area);
            }
        }
    }                                        

    private void rdoGetPCActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(rdoGetPC.isSelected())
        {
            rdoGetAC.setEnabled(false);
            try
            {
                temp = txtInputCR.getText();
                radius = Double.parseDouble(temp);
            }
            catch(NumberFormatException errors)
            {
                JOptionPane.showMessageDialog(null, "Enter the correct input!");   
            }
            finally
            {
                perimeter = 2.0 * (pi * radius);
                txtGetResultA.setText("Circumference: " + perimeter);
            }
            
        }   
    }                                        

    private void rdoRectangleActionPerformed(java.awt.event.ActionEvent evt) {                                             
        if(rdoRectangle.isSelected())
        {
            disabledSetA();
            disabledSetC();
            txtInputUL.setEnabled(true);
            txtInputUW.setEnabled(true);
            rdoGetRA.setEnabled(true);
            rdoGetRP.setEnabled(true);
        }
    }                                            

    private void rdoGetRAActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(rdoGetRA.isSelected())
        {
            rdoGetRP.setEnabled(false);
            try
            {
                temp = txtInputUL.getText();
                temp2 = txtInputUW.getText();
                length = Double.parseDouble(temp);
                width = Double.parseDouble(temp2);
            }
            catch(NumberFormatException errors)
            {
                JOptionPane.showMessageDialog(null, "Enter the correct input!");   
            }
            finally
            {
                area = length * width;
                txtGetResultB.setText("Area: " + area);
            }
            
        }
    }                                        

    private void rdoGetRPActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(rdoGetRP.isSelected())
        {
            rdoGetRA.setEnabled(false);
            try
            {
                temp = txtInputUL.getText();
                temp2 = txtInputUW.getText();
                length = Double.parseDouble(temp);
                width = Double.parseDouble(temp2);
            }
            catch(NumberFormatException errors)
            {
                JOptionPane.showMessageDialog(null, "Enter the correct input!");   
            }
            finally
            {
                perimeter = (2.0 * length) + (2.0 * width);
                txtGetResultB.setText("Perimeter: " + perimeter);
            }
            
        }
    }                                        

    private void rdoSquareActionPerformed(java.awt.event.ActionEvent evt) {                                          
        disabledSetA();
        disabledSetB();
        txtInputSS.setEnabled(true);
        rdoGetSA.setEnabled(true);
        rdoGetSP.setEnabled(true);
    }                                         

    private void rdoGetSAActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(rdoGetSA.isSelected())
        {
            rdoGetSP.setEnabled(false);
            try
            {
                temp = txtInputSS.getText();
                side = Double.parseDouble(temp);
            }
            catch(NumberFormatException errors)
            {
                JOptionPane.showMessageDialog(null, "Enter the correct input!");   
            }
            finally
            {
                area = side * side;
                txtGetResultC.setText("Area: " + area);
            }
            
        }
    }                                        

    private void rdoGetSPActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(rdoGetSP.isSelected())
        {
            rdoGetSA.setEnabled(false);
            try
            {
                temp = txtInputSS.getText();
                side = Double.parseDouble(temp);
            }
            catch(NumberFormatException errors)
            {
                JOptionPane.showMessageDialog(null, "Enter the correct input!");   
            }
            finally
            {
                perimeter = side * 4.0;
                txtGetResultC.setText("Perimeter: " + perimeter);
            }
            
        }
    }                                        
    
    public void enabledFirstThree()
    {
        rdoCircle.setEnabled(true);
        rdoRectangle.setEnabled(true);
        rdoSquare.setEnabled(true);
        rdoCircle.setSelected(false);
        rdoRectangle.setSelected(false);
        rdoSquare.setSelected(false);
    }
    
    public void disableAllItems()
    {
        txtInputCR.setText("");
        txtInputUL.setText("");
        txtInputUW.setText("");
        txtInputSS.setText("");
        txtGetResultA.setText("");
        txtGetResultB.setText("");
        txtGetResultC.setText("");
        
        disabledSetA();
        disabledSetB();
        disabledSetC(); 
    }
    
    public void disabledSetA()
    {
        rdoCircle.setEnabled(false);
        txtInputCR.setEnabled(false);
        txtGetResultA.setEnabled(false);
        rdoGetAC.setEnabled(false);
        rdoGetPC.setEnabled(false);
        rdoGetAC.setSelected(false);
        rdoGetPC.setSelected(false);
    }
    public void disabledSetB()
    {
        rdoRectangle.setEnabled(false);
        txtInputUL.setEnabled(false);
        txtInputUW.setEnabled(false);
        txtGetResultB.setEnabled(false);
        rdoGetRA.setEnabled(false);
        rdoGetRP.setEnabled(false);
        rdoGetRA.setSelected(false);
        rdoGetRP.setSelected(false);
    }
    
    public void disabledSetC()
    {
        rdoSquare.setEnabled(false);
        txtInputSS.setEnabled(false);
        txtGetResultC.setEnabled(false);
        rdoGetSA.setEnabled(false);
        rdoGetSP.setEnabled(false);
        rdoGetSA.setSelected(false);
        rdoGetSP.setSelected(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCircle;
    private javax.swing.JLabel lblRectangle;
    private javax.swing.JLabel lblSquare;
    private javax.swing.JRadioButton rdoCircle;
    private javax.swing.JRadioButton rdoGetAC;
    private javax.swing.JRadioButton rdoGetPC;
    private javax.swing.JRadioButton rdoGetRA;
    private javax.swing.JRadioButton rdoGetRP;
    private javax.swing.JRadioButton rdoGetSA;
    private javax.swing.JRadioButton rdoGetSP;
    private javax.swing.JRadioButton rdoRectangle;
    private javax.swing.JRadioButton rdoSquare;
    private javax.swing.JTextField txtGetResultA;
    private javax.swing.JTextField txtGetResultB;
    private javax.swing.JTextField txtGetResultC;
    private javax.swing.JTextField txtInputCR;
    private javax.swing.JTextField txtInputSS;
    private javax.swing.JTextField txtInputUL;
    private javax.swing.JTextField txtInputUW;
    // End of variables declaration                   
}
